# Generated by Django 6.0.6 on 2026-06-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('order', 'New Order'), ('response', 'Order Response'), ('subscription', 'Subscription'), ('system', 'System')], max_length=20)),
                ('channel', models.CharField(choices=[('dashboard', 'Dashboard'), ('email', 'Email'), ('whatsapp', 'WhatsApp')], default='dashboard', max_length=20)),
                ('title_en', models.CharField(max_length=255)),
                ('title_ar', models.CharField(max_length=255)),
                ('message_en', models.TextField()),
                ('message_ar', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
